server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# H2 configuration.
spring.datasource.url = jdbc:h2:file:./data/iot24;AUTO_SERVER=TRUE
spring.datasource.username = sa
spring.datasource.password =
spring.jpa.hibernate.ddl-auto = update
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console

mqtt.broker.address=tcp://127.0.0.1:1883
mqtt.broker.username=
mqtt.broker.password=

# To improve the performance during development.
vaadin.allowed-packages = com.vaadin,org.vaadin,dev.hilla,de.feswiesbaden.iot,com.github.appreciated
